Repository Team-Ampersand/GKR-Android-Admin, pull requests merged in 2023-09, with the labels that each got.

#154 🔀 :: (#153) Feature - change equipment modification api logic
  data/src/main/java/com/mpersand/data/network/api/EquipmentApi.kt
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/repository/EquipmentRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/java/com/mpersand/domain/repository/EquipmentRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/equipment/ModifyEquipmentUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/view/equipment/EquipmentScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/equipment/EquipmentViewModel.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#155 🔀 :: (#148) Feature - change violation api logic
  data/src/main/java/com/mpersand/data/dto/violation/request/ViolationRequest.kt
  domain/src/main/java/com/mpersand/domain/model/violation/request/ViolationRequestModel.kt
  presentation/src/main/java/com/mpersand/presentation/view/violation/ViolationScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/violation/component/ViolationDialog.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/violation/ViolationViewModel.kt
Labels: 1️⃣ Priority: High, 📬 Type: API, 🔨 Type: Refector

#157 🔀 :: (#156) sign in model type
  data/src/main/java/com/mpersand/data/dto/auth/response/SignInResponse.kt
  data/src/main/java/com/mpersand/data/network/RequestInterceptor.kt
  domain/src/main/java/com/mpersand/domain/model/auth/response/SignInResponseModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/auth/AuthViewModel.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug
