Repository Team-Ampersand/GKR-Android-Admin, pull requests merged in 2023-07, with the labels that each got.

#14 🔀 :: (#13) Feature - write auth data logic
  data/src/main/java/com/mpersand/data/remote/datasource/.gitkeep
  data/src/main/java/com/mpersand/data/remote/datasource/auth/AuthDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/auth/AuthDataSourceImpl.kt
  di/src/main/java/com/mpersand/di/modules/RemoteDataSourceModule.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#16 🔀 :: (#15) Feature - write auth domain logic
  data/src/main/java/com/mpersand/data/dto/auth/request/SignInRequest.kt
  data/src/main/java/com/mpersand/data/dto/auth/response/SignInResponse.kt
  data/src/main/java/com/mpersand/data/repository/.gitkeep
  data/src/main/java/com/mpersand/data/repository/AuthRepositoryImpl.kt
  di/src/main/java/com/mpersand/di/modules/RepositoryModule.kt
  domain/build.gradle.kts
  domain/src/main/java/com/mpersand/domain/model/.gitkeep
  domain/src/main/java/com/mpersand/domain/model/auth/request/SignInRequestModel.kt
  domain/src/main/java/com/mpersand/domain/model/auth/response/SignInResponseModel.kt
  domain/src/main/java/com/mpersand/domain/repository/.gitkeep
  domain/src/main/java/com/mpersand/domain/repository/AuthRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/.gitkeep
  domain/src/main/java/com/mpersand/domain/usecase/auth/SignInUseCase.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#18 🔀 :: (#17) Feature - write auth viewmodel logic
  .github/workflows/android.yml
  presentation/build.gradle.kts
  presentation/src/main/java/com/mpersand/presentation/view/auth/SignInScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/.gitkeep
  presentation/src/main/java/com/mpersand/presentation/viewmodel/AuthViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#20 🔀 :: (#19) Feature - modify signin page design
  .gitignore
  presentation/src/main/java/com/mpersand/presentation/view/auth/SignInScreen.kt
Labels: 2️⃣ Priortiy: Medium, ⚡Type: Simple

#22 🔀 :: (#21) Feature - write token interceptor logic
  data/build.gradle.kts
  data/src/main/java/com/mpersand/data/local/datasource/.gitkeep
  data/src/main/java/com/mpersand/data/local/datasource/LocalDataSource.kt
  data/src/main/java/com/mpersand/data/local/datasource/LocalDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/network/RequestInterceptor.kt
  data/src/main/java/com/mpersand/data/network/api/.gitkeep
  data/src/main/java/com/mpersand/data/network/api/AuthApi.kt
  data/src/main/java/com/mpersand/data/remote/datasource/auth/AuthDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/repository/AuthRepositoryImpl.kt
  di/src/main/java/com/mpersand/di/modules/LocalDataSourceModule.kt
  di/src/main/java/com/mpersand/di/modules/NetworkModule.kt
  domain/src/main/java/com/mpersand/domain/exception/TokenExpiredException.kt
  domain/src/main/java/com/mpersand/domain/repository/AuthRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/auth/SaveTokenUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/AuthViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#24 🔀 :: (#23) Feature - modify signin view overlapping
  presentation/src/main/java/com/mpersand/presentation/view/auth/SignInScreen.kt
Labels: 2️⃣ Priortiy: Medium, 🐞 Type: Bug

#26 🔀 :: (#25) Feature - write uistate exception handling
  buildSrc/src/main/java/Dependencies.kt
  data/src/main/java/com/mpersand/data/remote/datasource/auth/AuthDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/remote/util/SafeApiCall.kt
  domain/src/main/java/com/mpersand/domain/exception/HttpException.kt
  domain/src/main/java/com/mpersand/domain/exception/NoInternetException.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/mpersand/presentation/viewmodel/AuthViewModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/ExceptionHandling.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/util/UiState.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#28 🔀 :: (#27) Feature - main screen publishing
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/AppBar.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/FilterItem.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/StudentItem.kt
  presentation/src/main/res/drawable/ic_bell.xml
  presentation/src/main/res/drawable/ic_hamburger.xml
  presentation/src/main/res/drawable/ic_search.xml
  presentation/src/main/res/font/inter_light.ttf
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#30 🔀 :: (#29) Feature - detail screen publishing
  presentation/src/main/java/com/mpersand/presentation/view/detail/DetailScreen.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#32 🔀 :: (#31) Feature - write signin screen uistate logic
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mpersand/gkr_android_admin/GKRAdminNavHost.kt
  presentation/src/main/java/com/mpersand/presentation/view/auth/SignInScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/auth/navigation/SignInNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/navigation/MainNavigation.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#35 🔀 :: (#34) Feature - write main screen remote logic
  data/src/main/java/com/mpersand/data/dto/equpiment/response/EquipmentResponse.kt
  data/src/main/java/com/mpersand/data/network/api/EquipmentApi.kt
  di/src/main/java/com/mpersand/di/modules/NetworkModule.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#37 🔀 :: (#36) Feature - write main screen data logic
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSourceImpl.kt
  di/src/main/java/com/mpersand/di/modules/RemoteDataSourceModule.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#39 🔀 :: (#38) Feature - write main screen domain logic
  data/src/main/java/com/mpersand/data/dto/equpiment/response/EquipmentResponse.kt
  data/src/main/java/com/mpersand/data/repository/EquipmentRepositoryImpl.kt
  di/src/main/java/com/mpersand/di/modules/RepositoryModule.kt
  domain/src/main/java/com/mpersand/domain/model/equipment/response/EquipmentResponseModel.kt
  domain/src/main/java/com/mpersand/domain/repository/EquipmentRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/equipment/GetEquipmentsByFilterUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/equipment/GetRentedEquipmentsUseCase.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#41 🔀 :: (#40) Feature - write main screen viewmodel logic
  buildSrc/src/main/java/Dependencies.kt
  buildSrc/src/main/java/Versions.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/mpersand/presentation/view/auth/SignInScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/EquipmentItem.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/auth/AuthViewModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/main/MainViewModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/util/ExceptionHandling.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#43 🔀 :: (#42) Feature - add interceptor in network module
  di/src/main/java/com/mpersand/di/modules/NetworkModule.kt
Labels: 0️⃣ Priority: Critical, ✨ Type: Feature

#45 (#44) Feature - main screen navigation drawer
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/AppBar.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/NavigationDrawer.kt
  presentation/src/main/res/drawable/ic_exit_door.xml
  presentation/src/main/res/drawable/ic_folder.xml
  presentation/src/main/res/drawable/ic_handshake.xml
  presentation/src/main/res/drawable/ic_profile.xml
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#47 🔀 :: (#46) Feature - change app icon
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: 2️⃣ Priortiy: Medium, 🎨 Type: Publishing

#50 🔀 :: (#49) Feature - modify navigation drawer item
  presentation/src/main/java/com/mpersand/presentation/view/main/component/NavigationDrawer.kt
Labels: 2️⃣ Priortiy: Medium, ⚡Type: Simple

#53 🔀 :: (#52) Feature - write detail screen remote logic
  data/src/main/java/com/mpersand/data/dto/repair/request/RepairRequest.kt
  data/src/main/java/com/mpersand/data/dto/repair/response/RepairResponse.kt
  data/src/main/java/com/mpersand/data/network/api/EquipmentApi.kt
  data/src/main/java/com/mpersand/data/network/api/RepairApi.kt
  di/src/main/java/com/mpersand/di/modules/NetworkModule.kt
Labels: 1️⃣ Priority: High, 📬 Type: API

#54 🔀 :: (#48) Feature - violation screen publishing
  presentation/src/main/java/com/mpersand/presentation/view/component/GKRToolbar.kt
  presentation/src/main/java/com/mpersand/presentation/view/violation/ViolationScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/violation/component/ViolationItem.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#56 🔀 :: (#55) Feature - write detail screen data logic
  data/src/main/java/com/mpersand/data/network/api/EquipmentApi.kt
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/remote/datasource/repair/RepairDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/repair/RepairDataSourceImpl.kt
  di/src/main/java/com/mpersand/di/modules/RemoteDataSourceModule.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#58 🔀 :: (#57) Feature - write violation screen remote logic
  data/src/main/java/com/mpersand/data/dto/order/response/OrderResponse.kt
  data/src/main/java/com/mpersand/data/dto/violation/request/ViolationRequest.kt
  data/src/main/java/com/mpersand/data/network/api/OrderApi.kt
  data/src/main/java/com/mpersand/data/network/api/ViolationApi.kt
  di/src/main/java/com/mpersand/di/modules/NetworkModule.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#62 🔀 :: (#59) Feature - write detail screen domain logic
  data/src/main/java/com/mpersand/data/dto/repair/request/RepairRequest.kt
  data/src/main/java/com/mpersand/data/dto/repair/response/RepairResponse.kt
  data/src/main/java/com/mpersand/data/repository/EquipmentRepositoryImpl.kt
  data/src/main/java/com/mpersand/data/repository/RepairRepositoryImpl.kt
  di/src/main/java/com/mpersand/di/modules/RepositoryModule.kt
  domain/src/main/java/com/mpersand/domain/model/repair/request/RepairRequestModel.kt
  domain/src/main/java/com/mpersand/domain/model/repair/response/RepairResponseModel.kt
  domain/src/main/java/com/mpersand/domain/repository/EquipmentRepository.kt
  domain/src/main/java/com/mpersand/domain/repository/RepairRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/equipment/GetEquipmentDetailUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/repair/GetRepairHistoryUseCase.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#61 🔀 :: (#60) Feature - write violation screen data logic
  data/src/main/java/com/mpersand/data/network/api/OrderApi.kt
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/remote/datasource/violation/ViolationDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/violation/ViolationDataSourceImpl.kt
  di/src/main/java/com/mpersand/di/modules/RemoteDataSourceModule.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#65 🔀 :: (#64) Feature - write violation screen domain logic
  data/src/main/java/com/mpersand/data/dto/order/response/OrderResponse.kt
  data/src/main/java/com/mpersand/data/dto/violation/request/ViolationRequest.kt
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/repository/OrderRepositoryImpl.kt
  data/src/main/java/com/mpersand/data/repository/ViolationRepositoryImpl.kt
  di/src/main/java/com/mpersand/di/modules/RepositoryModule.kt
  domain/src/main/java/com/mpersand/domain/model/order/response/OrderResponseModel.kt
  domain/src/main/java/com/mpersand/domain/model/violation/request/ViolationRequestModel.kt
  domain/src/main/java/com/mpersand/domain/repository/OrderRepository.kt
  domain/src/main/java/com/mpersand/domain/repository/ViolationRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/order/GetNoReturnStudentsUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/violation/PostViolationUserUseCase.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#67 🔀 :: (#66) Feature - write violation screen viewmodel logic
  presentation/src/main/java/com/mpersand/presentation/view/violation/ViolationScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/violation/ViolationViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#69 🔀 :: (#63) Feature - write detail screen viewmodel logic
  app/src/main/java/com/mpersand/gkr_android_admin/GKRAdminNavHost.kt
  data/src/main/java/com/mpersand/data/dto/repair/request/RepairRequest.kt
  data/src/main/java/com/mpersand/data/network/api/RepairApi.kt
  data/src/main/java/com/mpersand/data/remote/datasource/repair/RepairDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/repair/RepairDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/repository/RepairRepositoryImpl.kt
  domain/src/main/java/com/mpersand/domain/model/repair/request/RepairRequestModel.kt
  domain/src/main/java/com/mpersand/domain/repository/RepairRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/repair/GetRepairHistoryUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/view/detail/DetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/detail/navigation/DetailNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/navigation/MainNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/detail/DetailViewModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/util/CombineResults.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#72 🔀 :: (#70) Feature - add safe api call logic
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/remote/datasource/repair/RepairDataSourceImpl.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#74 🔀 :: (#73) Feature - write logout remote logic
  data/src/main/java/com/mpersand/data/network/api/UserApi.kt
  di/src/main/java/com/mpersand/di/modules/NetworkModule.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#76 🔀 :: (#75) Feature - write logout data logic
  data/src/main/java/com/mpersand/data/remote/datasource/user/UserDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/user/UserDataSourceImpl.kt
  di/src/main/java/com/mpersand/di/modules/RemoteDataSourceModule.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#71 🔀 :: (#68) Feature - write violation screen navigation logic
  app/src/main/java/com/mpersand/gkr_android_admin/GKRAdminNavHost.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/NavigationDrawer.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/navigation/MainNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/violation/ViolationScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/violation/navigation/ViolationNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/violation/ViolationViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#81 🔀 :: (#80) Feature - write violation screen violation logic
  presentation/src/main/java/com/mpersand/presentation/view/violation/ViolationScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/violation/component/ViolationDialog.kt
  presentation/src/main/java/com/mpersand/presentation/view/violation/component/ViolationItem.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#82 🔀 :: (#79) Feature - write logout viewmodel logic
  app/src/main/java/com/mpersand/gkr_android_admin/GKRAdminNavHost.kt
  data/src/main/java/com/mpersand/data/network/api/UserApi.kt
  presentation/src/main/java/com/mpersand/presentation/view/auth/navigation/SignInNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/LogoutDialog.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/NavigationDrawer.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/navigation/MainNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/main/MainViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#85 🔀 :: (#84) Feature - write modify screen remote logic
  data/src/main/java/com/mpersand/data/dto/repair/request/RepairRequest.kt
  data/src/main/java/com/mpersand/data/network/api/EquipmentApi.kt
  data/src/main/java/com/mpersand/data/network/api/RepairApi.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#87 🔀 :: (#86) Feature - write modify screen data logic
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/remote/datasource/repair/RepairDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/repair/RepairDataSourceImpl.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#88 🔀 :: (#82) Fix- main filter click 할때 흰 화면이 나오는 오류 수정
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug

#90 🔀 :: (#89) Feature - write modify screen domain logic
  data/src/main/java/com/mpersand/data/dto/repair/request/RepairRequest.kt
  data/src/main/java/com/mpersand/data/repository/EquipmentRepositoryImpl.kt
  data/src/main/java/com/mpersand/data/repository/RepairRepositoryImpl.kt
  domain/src/main/java/com/mpersand/domain/model/repair/request/RepairRequestModel.kt
  domain/src/main/java/com/mpersand/domain/repository/EquipmentRepository.kt
  domain/src/main/java/com/mpersand/domain/repository/RepairRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/equipment/ModifyEquipmentUseCase.kt
  domain/src/main/java/com/mpersand/domain/usecase/repair/ModifyRepairHistoryUseCase.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#92 🔀 :: (#91) Feature - modify screen publishing
  app/src/main/java/com/mpersand/gkr_android_admin/GKRAdminNavHost.kt
  presentation/src/main/java/com/mpersand/presentation/view/modify/ModifyScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/modify/component/ModifyTextField.kt
  presentation/src/main/java/com/mpersand/presentation/view/modify/navigation/ModifyNavigation.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#94 🔀 :: (#93) Feature - modify repair screen publishing
  app/src/main/java/com/mpersand/gkr_android_admin/GKRAdminNavHost.kt
  presentation/src/main/java/com/mpersand/presentation/view/component/ModifyTextField.kt
  presentation/src/main/java/com/mpersand/presentation/view/equipment/EquipmentScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/equipment/navigation/EquipmentNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/modify/navigation/ModifyNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/repair/RepairScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/repair/navigation/RepairNavigation.kt
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#97 🔀 :: (#96) Feature - write equipment screen viewmodel logic
  app/src/main/java/com/mpersand/gkr_android_admin/GKRAdminNavHost.kt
  data/src/main/java/com/mpersand/data/dto/equpiment/request/EquipmentRequest.kt
  data/src/main/java/com/mpersand/data/network/api/EquipmentApi.kt
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/remote/util/SafeApiCall.kt
  data/src/main/java/com/mpersand/data/repository/EquipmentRepositoryImpl.kt
  domain/src/main/java/com/mpersand/domain/exception/HttpException.kt
  domain/src/main/java/com/mpersand/domain/model/equipment/request/EquipmentRequestModel.kt
  domain/src/main/java/com/mpersand/domain/repository/EquipmentRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/equipment/ModifyEquipmentUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/view/detail/DetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/detail/navigation/DetailNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/equipment/EquipmentScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/equipment/navigation/EquipmentNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/repair/navigation/RepairNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/equipment/EquipmentViewModel.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/util/ExceptionHandling.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/util/UiState.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#99 🔀 :: (#98) Feature - write repair screen viewmodel logic
  app/src/main/java/com/mpersand/gkr_android_admin/GKRAdminNavHost.kt
  data/src/main/java/com/mpersand/data/network/api/RepairApi.kt
  data/src/main/java/com/mpersand/data/remote/datasource/repair/RepairDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/repair/RepairDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/repository/RepairRepositoryImpl.kt
  domain/src/main/java/com/mpersand/domain/repository/RepairRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/repair/AddRepairHistoryUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/view/repair/RepairScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/repair/navigation/RepairNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/repair/RepairViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#101 🔀 :: (#100) Feature - add repair history to detail screen
  presentation/src/main/java/com/mpersand/presentation/view/detail/DetailScreen.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#103 🔀 :: (#102) Feature - custom clickable
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/AppBar.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/FilterItem.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/NavigationDrawer.kt
  presentation/src/main/java/com/mpersand/presentation/view/modifier/GKRClickable.kt
  presentation/src/main/java/com/mpersand/presentation/view/repair/RepairScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/violation/ViolationScreen.kt
Labels: 2️⃣ Priortiy: Medium, ✨ Type: Feature

#105 🔀 :: (#104) Feature - violation snack bar bug
  presentation/src/main/java/com/mpersand/presentation/view/violation/ViolationScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/violation/component/ViolationDialog.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/violation/ViolationViewModel.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug

#107 🔀 :: (#106) Feature - write auto login logic
  data/src/main/java/com/mpersand/data/local/datasource/LocalDataSource.kt
  data/src/main/java/com/mpersand/data/local/datasource/LocalDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/mpersand/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/mpersand/domain/repository/AuthRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/auth/IsLoginUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/view/auth/SignInScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/auth/AuthViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#108 🔀 :: (#95) Feature - request page publishing
  app/src/main/java/com/mpersand/gkr_android_admin/GKRAdminNavHost.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/NavigationDrawer.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/navigation/MainNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/RequestDetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/RequestScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/component/RequestItem.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/navigation/RequestDetailNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/navigation/RequestNavigation.kt
  presentation/src/main/res/drawable/temp_equipment_image.png
  presentation/src/main/res/font/inter_black.ttf
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#110 🔀 :: (#109) Feature - empty repair history bug
  presentation/src/main/java/com/mpersand/presentation/view/detail/DetailScreen.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug

#112 🔀 :: (#111) Feature - use tag instead product number
  presentation/src/main/java/com/mpersand/presentation/view/detail/DetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/EquipmentItem.kt
Labels: 2️⃣ Priortiy: Medium, ✨ Type: Feature

#114 🔀 :: (#113) Feature - content edge to edge setting
  app/src/main/java/com/mpersand/gkr_android_admin/MainActivity.kt
  presentation/src/main/java/com/mpersand/presentation/view/auth/SignInScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/detail/DetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/equipment/EquipmentScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/NavigationDrawer.kt
  presentation/src/main/java/com/mpersand/presentation/view/repair/RepairScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/RequestDetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/RequestScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/violation/ViolationScreen.kt
Labels: 3️⃣ Priority: Low, 🎨 Type: Publishing

#120 🔀 :: (#119) Feature - request screen viewmodel logic
  data/src/main/java/com/mpersand/data/dto/order/response/WaitListResponse.kt
  data/src/main/java/com/mpersand/data/network/api/OrderApi.kt
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/repository/OrderRepositoryImpl.kt
  domain/src/main/java/com/mpersand/domain/model/order/response/WaitListResponseModel.kt
  domain/src/main/java/com/mpersand/domain/repository/OrderRepository.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/RequestScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/component/RequestItem.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/request/RequestViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#122 🔀 :: (#121) Feature - request info logic
  app/build.gradle.kts
  app/src/main/java/com/mpersand/gkr_android_admin/GKRAdminNavHost.kt
  buildSrc/src/main/java/ProjectProperties.kt
  domain/build.gradle.kts
  domain/src/main/java/com/mpersand/domain/model/order/response/WaitListResponseModel.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/mpersand/presentation/view/request/RequestDetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/RequestScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/component/RequestItem.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/data/RequestInfoNavType.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/navigation/RequestDetailNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/navigation/RequestNavigation.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#124 🔀 :: (#123) Feature - search publishing
  app/src/main/java/com/mpersand/gkr_android_admin/GKRAdminNavHost.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/AppBar.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/navigation/MainNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/SearchScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/component/SearchHistoryItem.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/component/SearchResultItem.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/navigation/SearchNavigation.kt
  presentation/src/main/res/drawable/ic_diagonal_arrow.xml
  presentation/src/main/res/drawable/ic_history_icon.xml
  presentation/src/main/res/drawable/ic_right_arrow.xml
Labels: 1️⃣ Priority: High, 🎨 Type: Publishing

#126 🔀 :: (#125) Feature - search logic
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/equipment/EquipmentDataSourceImpl.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/SearchScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/equipment/EquipmentViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#129 🔀 :: (#127) Feature - empty repair history bug
  presentation/src/main/java/com/mpersand/presentation/view/repair/RepairScreen.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug

#134 🔀 :: (#133) Feature - profile remote logic
  data/src/main/java/com/mpersand/data/dto/user/response/UserResponse.kt
  data/src/main/java/com/mpersand/data/network/api/UserApi.kt
Labels: 0️⃣ Priority: Critical, ✨ Type: Feature

#136 🔀 :: (#135) Feature - profile data logic
  data/src/main/java/com/mpersand/data/remote/datasource/user/UserDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/user/UserDataSourceImpl.kt
Labels: 0️⃣ Priority: Critical, ✨ Type: Feature

#141 🔀 :: (#140) Feature - profile viewmodel logic
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/NavigationDrawer.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/main/MainViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Type: Feature

#142 🔀 :: (#128) Fix - snackbar logic
  presentation/src/main/java/com/mpersand/presentation/view/violation/ViolationScreen.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug

#138 🔀 :: (#132) Feature - request accept/reject logic
  data/src/main/java/com/mpersand/data/dto/order/request/OrderRequest.kt
  data/src/main/java/com/mpersand/data/network/api/OrderApi.kt
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/repository/OrderRepositoryImpl.kt
  domain/src/main/java/com/mpersand/domain/model/order/request/OrderRequestModel.kt
  domain/src/main/java/com/mpersand/domain/repository/OrderRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/order/RequestResultUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/RequestDetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/request/RequestViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Type: Feature

#144 🔀 :: (#143) Fix - 간단 오류 해결
  presentation/src/main/java/com/mpersand/presentation/view/search/SearchScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/search/component/SearchResultItem.kt
  presentation/src/main/res/drawable/ic_temp_equipment_image.png
  presentation/src/main/res/drawable/temp_equipment_image.xml
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug
