Repository Team-Ampersand/GKR-Android-Admin, pull requests merged in 2023-11, with the labels that each got.

#181 🔀 (#180) :: rent detail screen
  app/src/main/java/com/mpersand/gkr_android_admin/GKRAdminNavHost.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/navigation/MainNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/view/rentDetail/RentDetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/rentDetail/navigation/RentDetailNavigation.kt
Labels: 2️⃣ Priortiy: Medium, 🎨 Type: Publishing

#182 🔀 :: (#177) rental logic
  app/src/main/java/com/mpersand/gkr_android_admin/GKRAdminNavHost.kt
  data/src/main/java/com/mpersand/data/dto/order/response/RentalInfoResponse.kt
  data/src/main/java/com/mpersand/data/network/api/OrderApi.kt
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSource.kt
  data/src/main/java/com/mpersand/data/remote/datasource/order/OrderDataSourceImpl.kt
  data/src/main/java/com/mpersand/data/repository/OrderRepositoryImpl.kt
  domain/src/main/java/com/mpersand/domain/model/order/response/RentalInfoResponseModel.kt
  domain/src/main/java/com/mpersand/domain/repository/OrderRepository.kt
  domain/src/main/java/com/mpersand/domain/usecase/order/GetRentalRequestDetailUseCase.kt
  presentation/src/main/java/com/mpersand/presentation/view/rentDetail/RentDetailScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/rentDetail/navigation/RentDetailNavigation.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/order/OrderViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#184 🔀 :: (#183) displayed equipment type instead name
  buildSrc/src/main/java/ProjectProperties.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/view/main/component/EquipmentItem.kt
  presentation/src/main/java/com/mpersand/presentation/view/request/component/RequestItem.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug

#187 🔀 :: (#185) displayed incorrect equipment on detail
  presentation/src/main/java/com/mpersand/presentation/view/main/MainScreen.kt
  presentation/src/main/java/com/mpersand/presentation/viewmodel/main/MainViewModel.kt
Labels: 0️⃣ Priority: Critical, 🐞 Type: Bug
